name: Publish npm package

on:
  push:
    branches:
      - main
    paths:
      - "../../index.ts"  # Triggers the workflow only when this specific file changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "21.4.0"
          registry-url: "https://registry.npmjs.org/"

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Install Dependencies
        run: npm install

      - name: Clean dist directory
        run: rm -rf dist/*

      - name: Compile TypeScript
        run: tsc

      - name: NPM Whoami and Dry Run Publish
        run: |
          npm whoami
          npm publish --dry-run

      - name: Build
        run: npm run build

      - name: Publish to npm
        run: npm publish --access public --tag paleo-helpers
